version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
